### ISSUE TITLE
The icon it is not PNG

### ISSUE THREAD

**Issue by alomar-mac** [Sven1603/mmm-moon-phase-display#1]
Hi 
awesome Module but the icon not transparent

Example New Moon
![Screen Shot 2020-03-23 at 8 05 02 PM](https://user-images.githubusercontent.com/47379574/77342716-aebac900-6d41-11ea-9f29-89b162b0e786.png)

**Comment by Sven1603** [comment]
Hi,

Glad you like the module! I updated the moon images to be circles. It now shows both the dark and light side with. Hope that works better for you. In case you have more suggestions, just shoot!

**Comment by alomar-mac** [comment]
Wonderful and beautiful work .... Thank you for the prompt response and interest, and in the future, if I can improve the transparency of the black part 

Thank you so much

**Comment by alomar-mac** [comment]
Thank you, excellent job
![Screen Shot 2020-04-04 at 4 08 06 AM](https://user-images.githubusercontent.com/47379574/78415404-2fbf6d80-762a-11ea-85e3-528bdfc2cc63.png)
